backend:
  name: git-gateway # Netlify Identity ve Git Gateway servisini kullanacağımızı belirtir
  branch: main # veya master, projenizin ana branch'i hangisiyse onu yazın

# Yüklenen resimlerin nereye kaydedileceğini ve sitede nasıl görüneceğini belirtir
media_folder: "static/images/uploads" # Yüklenen resimler bu klasöre gider
public_folder: "/images/uploads" # Sitenizdeki resimlerin yolu bu şekilde olur

collections:
  # Bu bölüm "Ürünler" sayfasını yönetmek için
  - name: "urunler" # CMS içinde kullanılacak kimlik (sadece harf ve rakam)
    label: "Ürünler" # Admin panelinde görünecek etiket
    folder: "_data/urunler" # Yönetilecek içeriklerin (markdown dosyaları) saklanacağı klasör
    create: true # Yeni ürün eklemeye izin ver
    slug: "{{slug}}" # Dosya adını başlığa göre otomatik oluşturur
    fields: # Her bir ürün için hangi alanların olacağı
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Açıklama", name: "description", widget: "markdown"}
      - {label: "Öne Çıkan Resim", name: "thumbnail", widget: "image"}
