backend:
  name: git-gateway
  branch: main # Veya master, deponuzdaki ana dalın adını yazın

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Gönderiler"
    folder: "_posts"
    create: true
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "İçerik", name: "body", widget: "markdown"}
