backend:
  name: github
  repo: kontekdedektor/ktd-cms-test.github.io
  branch: main
  app_id: Ov23liP0x09qZ7XWn6L0

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Yazılar"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "İçerik", name: "body", widget: "markdown"}
